"""Dump the live MCP tool manifest to stdout as JSON.

Usage::

    python -m app.cli.dump_mcp_manifest            # pretty-print
    python -m app.cli.dump_mcp_manifest --compact   # minified
    python -m app.cli.dump_mcp_manifest > mcp-tool-manifest.json

Used by ``make manifest`` to regenerate ``mcp-tool-manifest.json``.
Run in CI to fail the build if the committed manifest has drifted from
the live registry.
"""

from __future__ import annotations

import argparse
import json


def build_manifest() -> dict:
    import app.mcp  # noqa: F401 — trigger tool registration side-effects
    from app.mcp.registry import list_tools

    tools = list_tools()
    return {
        "_note": "Generated by `python -m app.cli.dump_mcp_manifest`. Do not edit by hand.",
        "_source": "app.mcp.registry — live at GET /api/v1/mcp/tools",
        "mcp_tools": [
            {
                "name": t.name,
                "description": t.description,
                "scope": t.scope,
                "parameters": t.schema,
            }
            for t in tools
        ],
        "mcp_servers": {
            "falcon-mcp": {
                "note": "External stdio MCP server — see AGENT_QUICKSTART.md for run instructions",
                "transport": "stdio",
            }
        },
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Dump MCP tool manifest as JSON")
    parser.add_argument("--compact", action="store_true", help="Minified output")
    args = parser.parse_args()

    manifest = build_manifest()
    if args.compact:
        print(json.dumps(manifest, separators=(",", ":")))
    else:
        print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
