#!/usr/bin/env python3
"""Remaining DLLs and incidents to complete the dataset."""
import json, os, urllib.request

API = "http://localhost:8010"
KEY = os.environ.get("SK_API_KEY", "YxjXShQyv8L_-X_1Qb6DDSF9JvPXGer5_yTztqgvCAQ")

def mcp_call(tool, args, timeout=30):
    data = json.dumps({"tool": tool, "args": args}).encode()
    req = urllib.request.Request(f"{API}/api/v1/mcp/call", data=data, headers={"X-API-Key": KEY, "Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read())

def create_entity(name, kind):
    try:
        r = mcp_call("create_entity", {"name": name, "kind": kind})
        return r.get("id")
    except:
        return None

def add_claim(eid, ctype, value, conf=1.0, src=""):
    if not eid: return
    try: mcp_call("create_claim", {"entity_id": eid, "claim_type": ctype, "value": value, "confidence": conf})
    except: pass

def dlls():
    print("\n=== Remaining DLLs ===")
    dlls = [
        {"name": "user32.dll", "desc": "Windows User API. Window management, message handling, input.", "exports": ["CreateWindowExA/W","ShowWindow","GetMessage","TranslateMessage","DispatchMessage","SendMessageA/W","PostMessageA/W","SetWindowsHookExA/W","CallNextHookEx","UnhookWindowsHookEx","GetAsyncKeyState","GetKeyState","MapVirtualKeyA/W","VkKeyScanA/W","GetKeyboardState","SetKeyboardState","LoadCursorA/W","SetCursor","GetCursorPos","SetCursorPos","GetForegroundWindow","SetForegroundWindow","FindWindowA/W","EnumWindows","GetWindowTextA/W","IsWindowVisible","MessageBoxA/W"], "abuse": "SetWindowsHookEx for keyloggers (WH_KEYBOARD_LL). GetAsyncKeyState for credential harvesting. FindWindow for anti-debugging (check for monitoring tools). SetWindowsHookEx for DLL injection via hook callback. SendMessage for shatter attacks (privilege escalation via window messages to elevated processes).", "detect": "Monitor for SetWindowsHookEx with WH_KEYBOARD_LL from non-UI processes. GetAsyncKeyState polling loops. Unusual FindWindow queries for security tool windows."},
        {"name": "wininet.dll", "desc": "Windows Internet API. HTTP/FTP client functions. Used by IE and applications for HTTP requests.", "exports": ["InternetOpenA/W","InternetOpenUrlA/W","InternetConnectA/W","HttpOpenRequestA/W","HttpSendRequestA/W","InternetReadFile","InternetCloseHandle","InternetSetOptionA/W","InternetQueryOptionA/W","InternetGetCookieA/W","InternetSetCookieA/W","FtpOpenFileA/W","FtpGetFileA/W","FtpPutFileA/W","FtpDeleteFileA/W","FtpRenameFileA/W","InternetCrackUrlA/W","InternetCreateUrlA/W"], "abuse": "InternetOpenUrl + InternetReadFile for C2 communication (simpler than winhttp). InternetSetCookie for session hijacking. HTTP downloads of payloads. Many malware families use wininet over raw sockets because it respects proxy settings and is less suspicious. Cobalt Strike can use wininet for C2.", "detect": "Network connections from wininet.dll in unusual processes. HTTP requests to suspicious domains. TLS fingerprinting. Proxy-aware C2 via InternetSetOption."},
        {"name": "winhttp.dll", "desc": "Windows HTTP Services. Modern HTTP client API. Preferred over wininet for services and background tasks.", "exports": ["WinHttpOpen","WinHttpConnect","WinHttpOpenRequest","WinHttpSendRequest","WinHttpReceiveResponse","WinHttpReadData","WinHttpCloseHandle","WinHttpSetOption","WinHttpQueryHeaders","WinHttpAddRequestHeaders","WinHttpGetProxyForUrl","WinHttpCrackUrl","WinHttpSetTimeouts"], "abuse": "Preferred by modern malware for C2 over wininet (no IE dependency). WinHttpOpen + WinHttpConnect + WinHttpSendRequest for C2. Supports TLS, proxies, and custom headers. Used by Cobalt Strike (WinHTTP communication profile). WinHttpGetProxyForUrl for proxy-aware C2. More stealthy than wininet for service processes.", "detect": "WinHTTP connections from non-browser processes. TLS fingerprinting (JA3). Unusual User-Agent strings. Connection patterns matching Cobalt Strike WinHTTP beacon."},
        {"name": "crypt32.dll", "desc": "Certificate and cryptographic messaging. X.509 handling, PKCS, SPC.", "exports": ["CertOpenStore","CertOpenSystemStoreA/W","CertEnumCertificatesInStore","CertFindCertificateInStore","CertGetCertificateContextProperty","CertFreeCertificateContext","CertCloseStore","CertAddCertificateContextToStore","CertDeleteCertificateFromStore","CryptDecodeObjectEx","CryptQueryObject","CryptExportPKCS8","PFXImportCertStore","CertVerifyTimeValidity"], "abuse": "PFXImportCertStore for installing stolen code signing certificates. CertDeleteCertificateFromStore for removing security certificates (SUNBURST tactic). CryptQueryObject for extracting certificates from signed binaries. Certificate store manipulation for trust chain attacks.", "detect": "Monitor CertDeleteCertificateFromStore calls. Track PFXImportCertStore from unusual processes. Certificate store modification alerts from non-IE/non-certificate-manager processes."},
        {"name": "ole32.dll", "desc": "COM/OLE core functions. Object activation, marshaling, monikers.", "exports": ["CoCreateInstance","CoGetClassObject","CoInitializeEx","CoUninitialize","CoRegisterClassObject","CoRevokeClassObject","CoMarshalInterface","CoUnmarshalInterface","CreateBindCtx","MkParseDisplayName","CoGetObject","CoCreateInstanceEx","CoInitializeSecurity","CoSetProxyBlanket"], "abuse": "CoCreateInstance for COM object hijacking (persistence via CLSID). CoGetObject for fileless execution via COM scriptlets (Squiblydoo variant). OLE embedding for malicious document delivery. COM surrogates for DLL side-loading. MarshalInterface for inter-process communication in post-exploitation.", "detect": "Monitor CoCreateInstance for suspicious CLSIDs. COM object registration from unusual processes. DCOM activation events (Event ID 1001 in Microsoft-Windows-DistributedCOM)."},
        {"name": "shell32.dll", "desc": "Windows Shell API. File associations, shell execution, shortcuts.", "exports": ["ShellExecuteA/W","ShellExecuteExA/W","SHGetFolderPathA/W","SHGetSpecialFolderPathA/W","SHGetFileInfoA/W","SHBrowseForFolderA/W","SHGetPathFromIDListA/W","SHChangeNotify","ExtractIconA/W","DragAcceptFiles","CommandLineToArgvW","SHFileOperationA/W","StrFormatByteSizeA/W"], "abuse": "ShellExecute for executing arbitrary programs (bypasses some command-line monitoring). Shell shortcuts (.lnk) for malware delivery. Shell folder redirection for persistence. SHGetFolderPath for discovering user profile paths for staging.", "detect": "ShellExecute from unusual parent processes. .lnk file creation in startup folders. Shell folder modification. Unusual ShellExecute targets (cmd.exe, powershell.exe via ShellExecute)."},
        {"name": "urlmon.dll", "desc": "URL Monikers. Download functions, MIME handling, protocol handlers.", "exports": ["URLDownloadToFileA/W","URLDownloadToCacheFileA/W","URLOpenBlockingStreamA/W","ObtainUserAgentString","CoInternetSetFeatureEnabled","FindMimeFromData","IsURLAllowed","CreateUri"], "abuse": "URLDownloadToFile — classic malware download function. Simpler than wininet/winhttp. Used by many trojan downloaders. Often called from VBScript/JScript in malicious documents. CoInternetSetFeatureEnabled for disabling security features.", "detect": "URLDownloadToFile calls with remote URLs. File creation from urlmon.dll in unusual directories. Network connections from processes loading urlmon without browser context."},
        {"name": "dbghelp.dll", "desc": "Debug Help Library. Symbol handling, minidump, process enumeration.", "exports": ["MiniDumpWriteDump","SymInitialize","SymCleanup","SymFromAddr","SymFromName","SymEnumSymbols","StackWalk64","ImageNtHeader","MiniDumpReadDumpStream","EnumerateLoadedModules64","SymGetModuleInfo64","SymLoadModule64","SymUnloadModule64"], "abuse": "MiniDumpWriteDump for LSASS memory dumping (credential harvesting without Mimikatz). Used by procdump (legitimate) and many custom dumpers. Alternative to lsass memory read. StackWalk64 for anti-debugging. SymEnumSymbols for code analysis.", "detect": "MiniDumpWriteDump targeting lsass.exe (detect via Sysmon Event ID 10 for process access + Event ID 11 for file creation of .dmp). Procdump usage against lsass. Handle to lsass with PROCESS_VM_READ followed by MiniDumpWriteDump."},
        {"name": "version.dll", "desc": "Version information querying. DLL side-loading target.", "exports": ["GetFileVersionInfoA/W","GetFileVersionInfoSizeA/W","VerQueryValueA/W","GetFileVersionInfoExA/W"], "abuse": "Extremely common DLL side-loading target. Many legitimate applications load version.dll early in their import table. Attackers place malicious version.dll in application directory to execute before the real DLL loads (DLL search order hijacking). Used by APT29, APT28, FIN7, Lazarus, and many ransomware groups. QakBot, IcedID, and BazarLoader all use version.dll side-loading.", "detect": "Monitor version.dll loads from non-system directories (not C:\\Windows\\System32). Sysmon Event ID 7 (Image Loaded) for version.dll from user-writable paths. Hash comparison of loaded version.dll against known good."},
        {"name": "taskschd.dll", "desc": "Task Scheduler API. Create, modify, delete scheduled tasks.", "exports": ["ITaskService","ITaskFolder","ITaskDefinition","IAction","IExecAction","ITrigger","IRegisteredTask","IRunningTask"], "abuse": "Scheduled task creation for persistence (most common persistence mechanism). schtasks.exe is the CLI wrapper. Tasks can run as SYSTEM, with highest privileges, at logon, on schedule. Used by virtually every APT and ransomware group. Task XML can execute PowerShell, cmd, or custom binaries. Creative scheduling: on idle, on event, at logon, daily, weekly, monthly.", "detect": "Sysmon Event ID 1 for schtasks.exe execution. Windows Event Log Event ID 106 (Task Registered) and 140 (Task Updated). Monitor for tasks running as SYSTEM with unusual executables. Task creation from non-admin processes."},
        {"name": "dnsapi.dll", "desc": "DNS Client API. DNS resolution, caching, dynamic update.", "exports": ["DnsQuery_A/W","DnsQueryEx","DnsAcquireContextHandle_A/W","DnsReleaseContextHandle","DnsExtractRecordsFromMessage_W","DnsFree","DnsModifyRecordsInSet_A/W","DnsValidateName_A/W","DnsWriteQuestionToBuffer_W"], "abuse": "DnsQuery for DNS-based C2 resolution (domain generation algorithms). DNS tunneling via TXT record queries. DNS exfiltration via subdomain encoding. Used by APT29 for DNS C2 (avonsmcloud.com). DGA malware uses DnsQuery for algorithmically generated domain resolution.", "detect": "High-volume DNS queries from single process. Unusual query types (TXT, NULL). Queries to newly registered domains. DNS query patterns matching known DGAs. Entropy analysis on queried subdomains."},
        {"name": "sspicli.dll", "desc": "Security Support Provider Interface. Authentication protocols (Kerberos, NTLM, Negotiate).", "exports": ["AcquireCredentialsHandleA/W","InitializeSecurityContextA/W","AcceptSecurityContext","CompleteAuthToken","DeleteSecurityContext","FreeContextBuffer","QuerySecurityContextToken","EncryptMessage","DecryptMessage","MakeSignature","VerifySignature","EnumerateSecurityPackagesA/W","InitSecurityInterfaceA/W"], "abuse": "SSPI for pass-the-hash and pass-the-ticket attacks (InitializeSecurityContext with stolen hashes/tickets). Kerberos and NTLM abuse for lateral movement. Custom SSP for credential harvesting (like mimilib.dll as SSP). EncryptMessage/DecryptMessage for intercepting or manipulating encrypted communication.", "detect": "Monitor for custom SSP registration (HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\Security Packages). Unusual AcquireCredentialsHandle from non-auth processes. SSP DLL loads from non-system paths."},
        {"name": "mpr.dll", "desc": "Multiple Provider Router. Network resource connections, credential management.", "exports": ["WNetAddConnection2A/W","WNetAddConnection3A/W","WNetCancelConnection2A/W","WNetGetConnectionA/W","WNetGetResourceInformationA/W","WNetGetUniversalNameA/W","WNetGetUserA/W","WNetOpenEnumA/W","WNetEnumResourceA/W","WNetCloseEnum"], "abuse": "WNetAddConnection2 for lateral movement via network shares using stolen credentials. WNetGetUser for credential discovery. Network resource enumeration for discovery of file shares and printers. Used for mapping shares before ransomware deployment.", "detect": "Network share connections from unusual processes. WNetAddConnection2 with remote server paths. Credential usage for remote share access. Unusual share enumeration patterns."},
        {"name": "samlib.dll", "desc": "SAM (Security Account Manager) client library. User/group account management.", "exports": ["SamConnect","SamOpenDomain","SamOpenUser","SamOpenGroup","SamOpenAlias","SamQueryInformationUser","SamSetInformationUser","SamEnumerateUsersInDomain","SamEnumerateGroupsInDomain","SamLookupNamesInDomain","SamLookupIdsInDomain","SamGetGroupsForUser","SamChangePasswordUser","SamCreateUser2InDomain","SamDeleteUser"], "abuse": "Direct SAM API calls for credential harvesting (SamQueryInformationUser for NTLM hashes via DCSync). SamEnumerateUsersInDomain for domain user enumeration. SamChangePasswordUser for password resetting. DCSync attack uses SamGetGroupsForUser + SamQueryInformationUser to extract password hashes without touching LSASS.", "detect": "Monitor for SamConnect from non-DC processes. DRSUAPI replication requests (Event ID 4662 for DS Replication extended rights). SamQueryInformationUser from unusual sources. Network connections to DC SAM/RPC ports."},
    ]
    for dll in dlls:
        eid = create_entity(dll["name"], "dll")
        if eid:
            add_claim(eid, "capability", {"text": dll["desc"], "exported_functions": dll["exports"], "function_count": len(dll["exports"])}, 1.0, "Microsoft PE reference, security research")
            add_claim(eid, "technique", {"text": dll["abuse"]}, 0.95, "MITRE ATT&CK, threat intel")
            add_claim(eid, "detection", {"text": dll.get("detect","")}, 0.9, "EDR research")
            print(f"  + {dll['name']} ({len(dll['exports'])} exports)")

def incidents():
    print("\n=== Remaining Incidents ===")
    incs = [
        {"name": "3CX Supply Chain Attack", "year": 2023, "desc": "North Korean (Lazarus) compromise of 3CX desktop app build pipeline. Trojanned update (Trader TraderX) distributed to 600K+ customers. Used as initial access for crypto heist targeting. Double supply chain: 3CX compromise via infected Trading Technologies software. First known cascading supply chain attack.", "actors": ["Lazarus Group"], "cves": [], "loss": "Unknown"},
        {"name": "XZ Utils Backdoor CVE-2024-3094", "year": 2024, "desc": "Social engineering attack on xz/liblzma compression library. Attacker (Jia Tan) spent 2+ years building trust as contributor, then injected backdoor into v5.6.0/5.6.1. Backdoor allowed unauthenticated RCE via SSH through systemd. Discovered by Andres Freund (Microsoft engineer) investigating 500ms SSH latency. CVSS 10.0. Affected most Linux distributions. Highlighted open-source supply chain vulnerability.", "actors": ["Unknown (Jia Tan persona)"], "cves": ["CVE-2024-3094"], "loss": "N/A (caught before exploitation)"},
    ]
    for inc in incs:
        eid = create_entity(inc["name"], "incident")
        if eid:
            add_claim(eid, "timeline", {"text": inc["desc"], "year": inc["year"], "loss": inc.get("loss", "")}, 1.0, "Public reporting")
            if inc.get("actors"): add_claim(eid, "relationship", {"text": f"Attributed to {', '.join(inc['actors'])}", "related_entity": inc["actors"][0], "relationship": "attributed_to"}, 0.85, "Public attribution")
            if inc.get("cves"): add_claim(eid, "vulnerability", {"text": f"CVEs: {', '.join(inc['cves'])}", "cves": inc["cves"]}, 1.0, "NVD")
            print(f"  + {inc['name']}")

def main():
    dlls()
    incidents()
    print("\n=== Done ===")

if __name__ == "__main__":
    main()
